from typing import List, Any

LLVM_VERSION: str

class ClangDriver:
    C: Any = ...
    CPlusPlus: Any = ...
    IncludeDirType: Any = ...
    O0: Any = ...
    O1: Any = ...
    O2: Any = ...
    O3: Any = ...
    OpenCL: Any = ...
    OptimizationLevel: Any = ...
    ProgrammingLanguage: Any = ...
    System: Any = ...
    User: Any = ...
    def __init__(self, arg0, arg1, arg2, arg3: List[str]) -> None: ...
    def addIncludeDir(self, arg0: str, arg1) -> None: ...
    def getFileName(self) -> str: ...
    def removeIncludeDir(self, arg0: str, arg1) -> None: ...
    def setFileName(self, arg0: str) -> None: ...
    def setCompilerBinary(self, path: str): ...
    def getCompilerBinary(self) -> str: ...

class ClangExtractor:
    def __init__(self, arg0: ClangDriver) -> None: ...
    def GraphFromString(self, *args, **kwargs) -> Any: ...
    def SeqFromString(self, *args, **kwargs) -> Any: ...
    def SeqGraphFromString(self, *args, **kwargs) -> Any: ...

class LLVMIRExtractor:
    def __init__(self, arg0: ClangDriver) -> None: ...
    def GraphFromString(self, *args, **kwargs) -> Any: ...
    def SeqFromString(self, *args, **kwargs) -> Any: ...

class Visitor:
    def __init__(self) -> None: ...
